# Generated by Django 5.2.8 on 2025-11-20 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantoptionvalue",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_options",
                to="products.productvariant",
                verbose_name="Product Variant",
            ),
        ),
    ]
