# Generated by Django 5.2.8 on 2025-11-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_designer"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="designed_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_designers",
                to="common.designer",
                verbose_name="Product designer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="designed_year",
            field=models.DateField(
                auto_now_add=True,
                default="2025-01-01",
                verbose_name="Product designed year",
            ),
            preserve_default=False,
        ),
    ]
