# Generated by Django 5.2.8 on 2025-11-26 06:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_productvariant_discount_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Discount price",
            ),
        ),
    ]
