# Generated by Django 5.2.8 on 2025-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Order Number"
            ),
        ),
    ]
