# Generated by Django 5.2.8 on 2025-11-14 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="phone_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+998\\d{9}$")
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
