# Generated by Django 5.0.6 on 2025-11-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("products", "0002_alter_productvariantoptionvalue_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="products.product",
                verbose_name="Related Products",
            ),
        ),
    ]
