# Generated by Django 5.2.8 on 2025-11-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Enter the title of the blog post.",
                max_length=255,
                unique=True,
                verbose_name="Title",
            ),
        ),
    ]
