# Generated by Django 5.2.8 on 2025-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="NewsLetter email",
                    ),
                ),
            ],
            options={
                "verbose_name": "NewsLetter",
                "verbose_name_plural": "NewsLetters",
            },
        ),
    ]
